version: '2'

services:

  docker-av:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-av
    
    volumes:
      - ./data/queue:/data/av/queue
      - ./data/ok:/data/av/ok
      - ./data/nok:/data/av/nok
      - ./clamav:/var/lib/clamav
      - ./maldetect:/usr/local/maldetect
    #command:
    # - /usr/local/install_alerts.sh email@example.net
    # - /usr/local/bin/duoscan.sh /path/to/scan
    
    networks:
      - avnetwork

networks:
  avnetwork:
